FROM ubuntu

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install vim -y
RUN apt-get install emacs -y
RUN apt-get install gcc -y
RUN apt-get install git -y

CMD /bin/sh

# docker build -t env_c .
# docker run -it env_c
